### ISSUE TITLE
No such file or directory: 'details\\_version' error when install

### ISSUE THREAD

**Issue by yantzu** [scopely-devops/details#4]
(AWS) C:\Python27\virtualenv\AWS\Scripts>pip install details
Downloading/unpacking details
  Downloading details-0.1.0.tar.gz
  Running setup.py (path:C:\Python27\virtualenv\AWS\build\details\setup.py) egg_info for package details
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Python27\virtualenv\AWS\build\details\setup.py", line 13, in <module>
        version=open(os.path.join('details', '_version')).read(),
    IOError: [Errno 2] No such file or directory: 'details\_version'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Python27\virtualenv\AWS\build\details\setup.py", line 13, in <module>

```
version=open(os.path.join('details', '_version')).read(),
```

IOError: [Errno 2] No such file or directory: 'details\_version'

**Comment by garnaat** [comment]
Thanks for reporting this.  The MANIFEST.in file was omitted from the github repo so the _version file was not being included in the packaged distribution on PyPI.  I have fixed that and updated with a 0.2.0 release that should take care of the problem.
